Исправил логику раздела Help по замечаниям
lvb555/derzn pull request #363
Opened 2022-11-02 19:34 UTC by AntonDMoskalev

1. Проблема. Не происходит переход из корня дерева "Оглавление помощи) - не находится страница.
2. При выдаче страницы помощи реквизит "Содержание" выдается как HTML-текст
3. Проблема. Неопубликованные категории все равно выдаются в оглавлении. Условие формулировалось чуть иначе, поскольку реквизит "Опубликовано" перенесен в другую таблицу. Но результат необходим по сути тот же.

2022-11-04 16:37 UTC, Intey requested changes

2022-11-04 16:37 UTC, Intey commented on help/views.py
>          return render(request, "help/help_404.html", {'nodes': nodes})
можно сделать несколько `except` конструкций.
Я вижу в целом проблему - достаем первый из списка. Лучше `get_or_404` или как-то так он называется. Тогда емли хелпа нет, то джанго сама покажет 404.

2022-11-05 06:35 UTC, AntonDMoskalev commented on help/views.py
>          return render(request, "help/help_404.html", {'nodes': nodes})
Мне нужно вызывать по заданию кастомную страницу, поэтому get_object_or_404 не подходит, также на сколько я помню он работает с первичным ключём, а я поиск делаю по связанным таблицам

2022-11-06 14:28 UTC, Intey approved these changes

2022-11-06 14:30 UTC, merged