добавлена кнопка удалить предложение эксперта, правки формы интервью …
lvb555/derzn pull request #397
Opened 2022-11-27 13:44 UTC by RaptorialThing

…согласно issue https://github.com/lvb555/derzn/issues/256
 В строке каждого предложения добавить пиктограмму "Удаление" (красный знак удаления)
 Проблема. При создании нового предложения по умолчанию все параметры его равны параметрам предыдущего предложения Этого быть не должно.

2022-12-01 17:35 UTC, sergeybv26 commented on drevo/templates/drevo/base.html
>    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"
Для чего bootstrap закомментирован? Это не сломает другие страницы на сайте?

2022-12-01 17:35 UTC, sergeybv26 commented on drevo/templates/drevo/expert_work_page/question_expertises.html
> +<!--<h2 class="center question"><a href="{% url 'zdetail' question.id %}">{{question.title}}</a></h2>-->
Если код уже не нужен, то его лучше удалить, не нужно оставлять закомментированным

2022-12-01 17:35 UTC, sergeybv26 commented on drevo/templates/drevo/expert_work_page/question_expertises.html
>  <script src="https://unpkg.com/htmx.org@1.7.0"
Думаю не стоит подключать скрипты с онлайн-ресурсов, так как он может оказаться недоступным

2022-12-01 17:35 UTC, sergeybv26 commented on drevo/test_views.py
> +# import pytest
Если код не нужен, его необходимо удалять.

2022-12-01 17:35 UTC, sergeybv26 commented on drevo/views/expert_work/interview_answer_expert_proposal_view.py
> +    Удаляет мнение эксперта по ответу на вопрос интервью
По моему, докстринг не совсем верный

2022-12-09 14:37 UTC, Intey commented on drevo/templates/drevo/expert_work_page/question_expertises.html
>  <script src="https://unpkg.com/htmx.org@1.7.0"
Это от меня. Эксперимент был не удачный.

2022-12-09 14:49 UTC, Intey requested changes

2022-12-09 14:49 UTC, Intey commented on drevo/views/expert_work/proposal_delete_view.py
> +        "question_expert_work", kwargs={"interview_pk": 1, "question_pk": 2}
Тут не должны быть захоржкожены идентификаторы.

2022-12-09 16:49 UTC, closed without merging