Max expert agree resolved conflicts
lvb555/derzn pull request #408
Opened 2022-12-01 14:50 UTC by RaptorialThing

resolved conflicts
issue #256 
Добавлено поле "Допустимое число ответов" на страницу [/interview/879/questions/818/expertise](https://test.derzn.ru/drevo/interview/879/questions/818/expertise)
добавил контроль максимального количества отметок чекбокса "С ответом согласен" ответов и предложений для эксперта по вопросу интервью
список максимального числа вопросов интервью [/drevo/max_agreed_list/](https://test.derzn.ru/drevo/max_agreed_list/)
создать новое максимальное число  [/drevo/max_agreed_create/](https://test.derzn.ru/drevo/max_agreed_create/)
страница максимального числа с кнопкой удалить это число  [/drevo/interview/4/questions/3/max_agreed/1](https://test.derzn.ru/drevo/interview/4/questions/3/max_agreed/1)

2022-12-01 16:20 UTC, RaptorialThing commented
@Intey

2022-12-01 17:54 UTC, sergeybv26 commented on drevo/forms/max_agreed_create_form.py
> +    def __init__(self, *args, **kwargs):
Для чего переопределен метод?

2022-12-01 17:54 UTC, sergeybv26 commented on drevo/admin.py
> +
Лишние строки

2022-12-01 17:54 UTC, sergeybv26 commented on drevo/models/interview_answer_expert_proposal.py
> +
Добавить докстринг

2022-12-01 17:54 UTC, sergeybv26 commented on drevo/templates/drevo/base.html
>    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"
Не сломает ли работу других страниц?

2022-12-01 17:54 UTC, sergeybv26 commented on drevo/views/expert_work/interview_answer_expert_proposal_view.py
> +    Удаляет мнение эксперта по ответу на вопрос интервью
Докстринг не верный

2022-12-01 17:54 UTC, sergeybv26 commented on drevo/views/max_agreed_question_delete_view.py
> +    def delete(self, request, *args, **kwargs):
Не понятно зачем переопределен метод

2022-12-01 17:54 UTC, sergeybv26 commented on drevo/views/max_agreed_question_create_view.py
> +    def get_context_data(self, **kwargs):
Не понятно зачем переопределены методы ниже

2022-12-02 09:22 UTC, Intey requested changes
По задаче 
> Необходим контроль максимального допустимого числа ответов, задаваемого метазнанием вида "Число", связанным со знанием - вопросом связью вида "Число ответов". Число ответов - общее число включенных чек-боксов вида "Ответ" и "Новый ответ"

Т.е. не стоило заводить новую модель и вот это все. Нужно мспользовать модель Znanie со связью к Tz с именем "Число ответов". Такое знание должно быть прилинковано к модели Znanie текущего интервью соответствующей связью.

2022-12-02 09:22 UTC, Intey commented on drevo/managers.py
> +        return super().get_queryset().all()
Зачем эти менеджеры? Они дублируют функционал тех, что есть по умолчанию.

2022-12-02 09:22 UTC, Intey commented on drevo/models/interview_answer_expert_proposal.py
> +        con3 = Q(author_id=prop.expert_id)
Именование условий не очень полезное. Лучше:
match_interview
match_author
match_question.
Но честно говоря я большого смысла в их выносе за скобки не вижу: они не переиспользуются,так что можно вставить их внутри скобки уже без Q, просто именованными аргументами.

2022-12-02 09:22 UTC, Intey commented on drevo/models/interview_answer_expert_proposal.py
> +            return True
Я предлагаю в первой строчке сразу применить .first. Тогда ниже не нужно брать по индексу и а max_agreed уже будет первая запись, если есть.

2022-12-02 11:19 UTC, RaptorialThing commented
@Intey @sergeybv26 замечания, кроме base.html, учтены

2022-12-02 15:12 UTC, RaptorialThing commented
> По задаче
> 
> > Необходим контроль максимального допустимого числа ответов, задаваемого метазнанием вида "Число", связанным со знанием - вопросом связью вида "Число ответов". Число ответов - общее число включенных чек-боксов вида "Ответ" и "Новый ответ"
> 
> Т.е. не стоило заводить новую модель и вот это все. Нужно мспользовать модель Znanie со связью к Tz с именем "Число ответов". Такое знание должно быть прилинковано к модели Znanie текущего интервью соответствующей связью.

Можно подробнее расписать? Создать новое Tz c name="Число ответов". Создать запись Znanie, связанно через tz  - создать новое Relation (bz_id,tr_id,rz_id,author_id,user_id). В этом Znanie  в поле content будет максимальное число  соглашений?

2022-12-02 23:18 UTC, closed without merging