Feature max answers
lvb555/derzn pull request #411
Opened 2022-12-02 23:17 UTC by RaptorialThing

2022-12-02 23:23 UTC, RaptorialThing commented
@Intey @alex4956   учтены замечания по ревью

2022-12-09 14:48 UTC, sergeybv26 approved these changes

2022-12-09 14:54 UTC, Intey requested changes

2022-12-09 14:54 UTC, Intey commented on drevo/models/interview_answer_expert_proposal.py
> +            & Q(is_agreed=True)
Здесь смысла в применении Q уже нет. Можно просто:

    filter(expert_id=usr_id, 
           question=prop.question_id, ...

И так далее

2022-12-09 14:54 UTC, Intey commented on drevo/views/expert_work/views.py
> +                & Q(user_id=self.request.user.id)
Аналогично насчет Q

2022-12-09 14:54 UTC, Intey commented on drevo/models/interview_answer_expert_proposal.py
> +                & Q(user_id=usr_id)
Аналогично, от Q можно избавиться.

2022-12-23 03:42 UTC, merged