Развитие функционала страницы "Работа руководителя по предложениям экспертов"
lvb555/derzn pull request #425
Opened 2022-12-23 20:33 UTC by Novak1656

2022-12-26 08:15 UTC, sergeybv26 commented on drevo/models/interview_results_schedule.py
> +    NOT_MORE_OFTEN = 1
Настройки лучше вынести в settings. Здесь сложно будет найти настройку

2022-12-26 08:15 UTC, sergeybv26 commented on drevo/migrations/0029_alter_glossaryterm_options_and_more.py
> +class Migration(migrations.Migration):
Миграции нужно будет синхронизировать с develop

2022-12-26 08:15 UTC, sergeybv26 commented on drevo/models/interview_results_schedule.py
> +        related_name='sending_schedule',
related_name пишется во множественном числе

2022-12-26 08:15 UTC, sergeybv26 commented on drevo/models/interview_results_schedule.py
> +        unique=True,
ForeignKey с параметром unique=True равносилен OneToOne

2022-12-26 08:15 UTC, sergeybv26 commented on drevo/models/interview_results_schedule.py
> +        auto_now_add=True
Зачем auto_now_add, если далее переопределяем метод save?

2022-12-26 08:15 UTC, sergeybv26 commented on drevo/models/interview_results_schedule.py
> +    last_sending = models.DateTimeField(
В каком случае будет обновляться эта дата?

2022-12-26 09:22 UTC, Valentin-Butorin requested changes

2022-12-26 09:22 UTC, Valentin-Butorin commented on drevo/views/admin_interview_work/interview_result_senders.py
> +            Q(interview__pk=self.interview.pk) & Q(expert=expert)
В Q нет необходимости

2022-12-26 09:22 UTC, Valentin-Butorin commented on drevo/views/admin_interview_work/interview_result_senders.py
> +            Q(bz=self.interview) & Q(rz__tz=Tz.objects.get(name='Вопрос'))
Тоже Q
rz__tz__name='Вопрос'

2022-12-26 09:22 UTC, Valentin-Butorin commented on drevo/views/admin_interview_work/interview_result_senders.py
> +            if proposal.status == 'ANSDPL' or proposal.status == 'RESDPL':
тут по идее elif должен быть, сейчас со статусом APPRVE попадет в not_accepted

2022-12-26 09:22 UTC, Valentin-Butorin commented on drevo/views/admin_interview_work/interview_result_senders.py
> +            Q(bz=self.interview) & Q(rz__tz=Tz.objects.get(name='Вопрос'))
То же, что и выше

2022-12-26 09:22 UTC, Valentin-Butorin commented on drevo/views/admin_interview_work/views.py
> +                schedule.save()
зачем сохранять объект, который не изменяется?

2022-12-26 09:22 UTC, Valentin-Butorin commented on drevo/views/admin_interview_work/interview_result_senders.py
> +                Q(bz__name=question) & Q(tr=Tr.objects.get(name='Ответ [ы]'))
без Q и tr__name

2022-12-26 09:22 UTC, Valentin-Butorin commented on drevo/views/admin_interview_work/views.py
> +                form.fields[field].widget.attrs['class'] = 'form-control'
Лучше всё, что связано с рендером, перенести в класс формы

2022-12-26 09:22 UTC, Valentin-Butorin commented on drevo/views/admin_interview_work/views.py
> +                    if not Relation.objects.filter(Q(bz=obj.question) & Q(rz=other_obj) & Q(user=obj.expert)).exists():
Q

2022-12-26 13:31 UTC, Valentin-Butorin commented on drevo/models/interview_results_schedule.py
> +        if (not self.pk) and (self.interview.tz.name != 'Интервью'):
Лучше сделать валидатор https://docs.djangoproject.com/en/4.1/ref/validators/

2022-12-26 13:31 UTC, Valentin-Butorin commented on drevo/models/interview_results_schedule.py
> +        self.next_sending = now() + datetime.timedelta(days=self.NOT_MORE_OFTEN)
Можно вынести в default поля next_sending

2022-12-26 16:20 UTC, Novak1656 commented on drevo/migrations/0029_alter_glossaryterm_options_and_more.py
> +class Migration(migrations.Migration):
Я уже провёл merge миграций (0036_merge_20221223_2358)

2022-12-26 16:20 UTC, Novak1656 commented on drevo/models/interview_results_schedule.py
> +        related_name='sending_schedule',
Знаю, но указал в единственном числе так как у одного интервью может быть только одна запись в бд связанная с рассылкой, я отталкивался от этого.

2022-12-26 16:26 UTC, Novak1656 commented on drevo/models/interview_results_schedule.py
> +    last_sending = models.DateTimeField(
При каждом вызове метода save

2022-12-26 16:28 UTC, Novak1656 commented on drevo/views/admin_interview_work/views.py
> +                schedule.save()
По задумке вызов данного метода изменяет время следующей возможной рассылки, так как данный функционал находится в переопределённом методе save

2022-12-26 16:29 UTC, Novak1656 commented on drevo/views/admin_interview_work/views.py
> +                form.fields[field].widget.attrs['class'] = 'form-control'
Форма не моя, а уже была давно написана кем-то другим, поэтому я решил изменить виджеты не в самом классе формы

2022-12-26 16:32 UTC, Novak1656 commented on drevo/models/interview_results_schedule.py
> +        self.next_sending = now() + datetime.timedelta(days=self.NOT_MORE_OFTEN)
Зачем?

2022-12-26 17:43 UTC, Valentin-Butorin commented on drevo/views/admin_interview_work/views.py
> +                schedule.save()
Значит, эту логику нужно вынести в отдельный метод и вызывать его
По методу save уже отписал

2022-12-26 17:46 UTC, Novak1656 commented on drevo/models/interview_results_schedule.py
> +        if (not self.pk) and (self.interview.tz.name != 'Интервью'):
Насколько я знаю validators=[...] проверяют данные на уровне django, но не бд. Если бы можно было добавлять новые записи в данную таблицу через админку, то да, валидатор бы пригодился, так как там он используется в форме. Однако в данном случае занести данные в таблицу через админку нельзя, а можно только просматривать. Добавление и обновление записей в данной таблице проходит автоматически.

2022-12-26 18:02 UTC, Novak1656 commented on drevo/views/admin_interview_work/views.py
> +                schedule.save()
Хорошо, тогда так и сделаю

2022-12-26 18:27 UTC, Valentin-Butorin commented on drevo/models/interview_results_schedule.py
> +        if (not self.pk) and (self.interview.tz.name != 'Интервью'):
Тогда можно вынести проверку в отдельный метод модели и проверять перед вызовом save

2022-12-26 18:43 UTC, Valentin-Butorin commented on drevo/views/admin_interview_work/views.py
> +                form.fields[field].widget.attrs['class'] = 'form-control'
То есть этому коду место здесь? Ни в классе формы, ни в методе get_form хотя бы, а именно в get_context_data?
Получается, мы второй раз создаем экземпляр формы и заменяем тот, который уже находится в context, да ещё и какие-то манипуляции с внешним видом формы производим.
Эта форма используется только в админке, вроде бы никаких изменений добавление form-control не должно вызвать.

2022-12-28 06:36 UTC, sergeybv26 approved these changes

2022-12-28 06:36 UTC, sergeybv26 commented on drevo/models/interview_results_schedule.py
> +        related_name='sending_schedule',
В таком случае тип связи должен быть OneToOne

2022-12-28 06:54 UTC, Novak1656 commented on drevo/models/interview_results_schedule.py
> +        related_name='sending_schedule',
Я внёс изменение связи в коммите [Внёс некоторые правки на основе комментариев](https://github.com/lvb555/derzn/pull/425/commits/4c7fa5dcb238ac19d831f3ccf9df028bbba330d1)

2022-12-28 09:39 UTC, Valentin-Butorin approved these changes

2022-12-28 12:47 UTC, merged