Т - Создание знания. Требование обязательности заполнения в контексте Вида знания. #42
lvb555/derzn pull request #448
Opened 2023-01-06 17:34 UTC by RakitDautov

Добавил поля is_author_required и is_href_required в модель TZ (knowledge_kind.py).
Добавил валидацию форм MyValidators, для полей author и href модели Znanie (knowledge.py), которая проверяет необходимость заполнения полей author и href в зависимости от значений is_author_required и is_href_required.

2023-01-08 11:25 UTC, DemidovEvg requested changes
Вопросы в комментах

2023-01-08 11:25 UTC, DemidovEvg commented on drevo/forms/knowledge_form.py
> +class MyValidators():
Предлагаю поменять название валидатора, так как 'мой валидатор' не особо говорит о том что это за валидатор) Название лучше либо по тому что делает, либо по тому к чему относится. И нужно ли отдельно валидаторы выносить? может прямо в форме сделать?

2023-01-08 11:25 UTC, DemidovEvg commented on drevo/forms/knowledge_form.py
> +        except AttributeError:
На сколько я понимаю по исходникам джанги при отсутсвии объекта в методе get рейзится исключение ObjectDoesNotExist(Exception), поэтому через AttributeError мы его не поймаем.

2023-01-08 11:25 UTC, DemidovEvg commented on drevo/forms/knowledge_form.py
> +        except AttributeError:
И кстати совместную проверку лучше проводить в методе clean() это более интуитивно

2023-01-08 11:25 UTC, DemidovEvg commented on drevo/forms/knowledge_form.py
> +        except AttributeError:
Подумай может сделать как-то так:
current_tz = Tz.objects.filter(id=kind.id).first() # Если нет объекта то None
if current_tz and current_tz.is_author_required and not author:
    raise ValidationError('Для данного вида знаний поле автор является обязательным!')

2023-01-08 11:25 UTC, DemidovEvg commented on drevo/forms/knowledge_form.py
> +    def clean_href(self):
Тут тоже самое что и для автора)

2023-01-08 11:25 UTC, DemidovEvg commented on drevo/models/knowledge_kind.py
> +        verbose_name='Автор обязателен для заполнения?'
Может убрать вопросы в verbose_name и сделать как утверждение?

2023-01-18 07:49 UTC, RakitDautov commented on drevo/forms/knowledge_form.py
> +class MyValidators():
Мы ипортируем этот класс в knowledge_create_form.py, я думаю лучше оставить его в отдельном классе

2023-01-18 10:40 UTC, DemidovEvg requested changes

2023-01-18 10:40 UTC, DemidovEvg commented on drevo/forms/knowledge_form.py
> +        except ObjectDoesNotExist:
Tz.DoesNotExist было бы красивее, но смотри сам)

2023-01-18 10:40 UTC, DemidovEvg commented on drevo/forms/knowledge_form.py
> +            print('Необходимо указать вид знания')
но тут вопрос логики, нам на форме нужно ошибку отобразить, а ты тут просто принт делаешь, как юзер узнает?, и мы в итоге не сломаем сохранение, и оно пройдет штатно, а при этом была ошибка

2023-01-18 10:40 UTC, DemidovEvg commented on drevo/models/knowledge_kind.py
>      objects = models.Manager()
а зачем objects = models.Manager()? это ведь дефолтно и так

2023-01-18 10:40 UTC, DemidovEvg commented on drevo/forms/knowledge_form.py
> +            print('Необходимо указать вид знания')
и тут исключения ObjectDoesNotExist ни кем не может быть вызвано, обработка по сути в никуда

2023-01-18 10:40 UTC, DemidovEvg commented on drevo/forms/knowledge_form.py
> +        author = self.cleaned_data['author']
может ли быть ситуация что в данных нет ключа 'author' или ключа 'tz'? Если может, тогда мы тут получим ошибку отсутствия ключа

2023-01-18 10:40 UTC, DemidovEvg commented on drevo/models/knowledge_kind.py
>      objects = models.Manager()
но это наверное не ты писал) тогда просьба просто это удалить)

2023-01-18 10:40 UTC, DemidovEvg commented on drevo/forms/knowledge_form.py
>          fields = '__all__'
Это тоже наверно не ты писал, но лучше указывать явно перечень полей для формы. Например здесь мы формируем в то числе поле для id, а оно не нужно

2023-01-18 12:19 UTC, DemidovEvg approved these changes

2023-01-18 12:20 UTC, DemidovEvg approved these changes

2023-01-18 12:21 UTC, merged