Reacting
lvb555/derzn pull request #672
Opened 2023-08-22 15:03 UTC by Dinarchak

Добавил кнопки лайка дизлайка и избранное на страницу тестов

2023-08-26 14:09 UTC, sergeybv26 requested changes

2023-08-26 14:09 UTC, sergeybv26 commented on .env.sample
> +export SECRET_KEY=asdaaskdw9u2r4lfkjd32
sample файл предназначен для того, чтобы показать какие переменные обязательны для запуска проекта. Установка значений по умолчанию, так где это допустимо осуществляется в файле settings.py.
Те значения, которые нельзя выкладывать в репозиторий, например Secret key, необходимо размещать в файле .env

2023-08-26 14:09 UTC, sergeybv26 commented on drevo/templates/drevo/reacting.html
> +                            style="color:#BFBFBF">
Зачем здесь стили, если создан css файл? Стили лучше размещать в css файле

2023-08-26 14:09 UTC, sergeybv26 commented on dz/settings.py
> +env.read_env('.env.sample')
это лишнее. нужно было создать файл .env

2023-08-26 19:26 UTC, Dinarchak commented on drevo/templates/drevo/reacting.html
> +                            style="color:#BFBFBF">
Стили на тегах устанавливал не я, они были в шаблоне, из которого я взял кнопки, поэтому решил не менять.

2023-08-27 06:15 UTC, sergeybv26 approved these changes

2023-08-28 19:39 UTC, sergeybv26 approved these changes

2023-08-29 17:28 UTC, merged