Issue#142
lvb555/derzn pull request #730
Opened 2023-10-23 17:55 UTC by HstrPrn

Реализовал решение задачи #142.
Settings.py и Dockerfile подгонял под себя, не знаю, насколько это может пригодиться кому то еще.

2023-10-25 18:03 UTC, sergeybv26 requested changes

2023-10-25 18:03 UTC, sergeybv26 commented on drevo/models/relation_type.py
> +    is_invert = models.BooleanField(editable=False,
Наименование поля не соответствует значению verbose_name

2023-10-25 18:03 UTC, sergeybv26 commented on dz/settings.py
> +if DEBUG:
На тестовом сервере приложение работает в debug режиме с MySQL

2023-10-25 18:03 UTC, sergeybv26 commented on drevo/migrations/0082_auto_20231023_2021.py
> +    ]
В предыдущем PR имеются тоже миграции. Возможно потребуется выполнять merge миграций

2023-10-25 18:30 UTC, HstrPrn commented on dz/settings.py
> +if DEBUG:
ок, это я чисто для себя сделал.

2023-10-25 18:30 UTC, HstrPrn commented on drevo/migrations/0082_auto_20231023_2021.py
> +    ]
можешь плиз объяснить этот момент в лс в телеге, не совсем понял

2023-10-25 18:30 UTC, HstrPrn commented on drevo/models/relation_type.py
> +    is_invert = models.BooleanField(editable=False,
исправлю

2023-10-28 19:08 UTC, sergeybv26 requested changes
Не вижу всех исправлений по предыдущему ревью

2023-10-28 20:52 UTC, HstrPrn commented
Напиши конкретнее плиз

2023-10-30 17:50 UTC, sergeybv26 reviewed
Необходимо исправить замечания и можно мерджить в develop без дополнительного согласования

2023-10-30 17:50 UTC, sergeybv26 commented on drevo/admin.py
> +            Relation.objects.filter(bz=obj.rz, rz=obj.bz, tr=obj.tr.invert_tr).delete()
Разве нельзя прописать правило в связанной модели on_delete? Нужен ли этот код?

2023-10-30 17:50 UTC, sergeybv26 commented on drevo/views/user_suggestion_view.py
> +        for t in knowledge.tz.available_suggestion_types.all():
Наименование переменной должно отражать информацию о том, что в ней содержится. t - не очень удачное наименование для переменной

2023-10-30 22:51 UTC, HstrPrn commented on drevo/admin.py
> +            Relation.objects.filter(bz=obj.rz, rz=obj.bz, tr=obj.tr.invert_tr).delete()
у нас по тз в модели Relations нет связи с самой собой. создание, изменение и удаление инверсной копии модели просиходит во вьюхах

2023-10-30 22:52 UTC, HstrPrn commented on drevo/views/user_suggestion_view.py
> +        for t in knowledge.tz.available_suggestion_types.all():
это не я писал, это после ребейса подтянулись изменения

2023-11-01 15:56 UTC, closed without merging