Доработки и модификации страницы znanie/id/questions_and_check_answers #691
lvb555/derzn pull request #731
Opened 2023-10-23 21:39 UTC by Allecs43rus

Проведены доработки в соответствии с замечаниями и дополнениями в задаче #691.

2023-10-25 18:05 UTC, sergeybv26 commented on drevo/models/questions.py
> +        null=True,
Думаю для этого поля лучше было бы установить значение по умолчанию вместо NULL

2023-10-25 18:21 UTC, Allecs43rus commented on drevo/models/questions.py
> +        null=True,
Поле было реализовано для установки порядка отображения на странице через админку. Я уточню этот момент у Леонида.

2023-10-25 18:25 UTC, sergeybv26 commented on drevo/models/questions.py
> +        null=True,
NULL не очень удачное значение для сортировки. Думаю лучше 0 поставить или 1 по умолчанию

2023-10-25 18:42 UTC, Allecs43rus commented on drevo/models/questions.py
> +        null=True,
Изменил

2023-10-25 18:46 UTC, sergeybv26 commented on drevo/models/questions.py
> +        null=True,
Не совсем верно. Для чего служит параметр blank, а для чего null? За что отвечают? https://docs.djangoproject.com/en/4.2/ref/models/fields/

2023-10-25 19:21 UTC, Allecs43rus commented on drevo/models/questions.py
> +        null=True,
Исключил пустые значения.

2023-10-25 19:42 UTC, Allecs43rus commented on drevo/models/questions.py
> +        null=True,
В проекте повсеместно используется принцип с NULL. За основу взял модель Znanie.

2023-10-26 11:01 UTC, sergeybv26 requested changes

2023-10-26 11:01 UTC, sergeybv26 commented on drevo/models/questions.py
> +        default=0
Где blank?

2023-10-26 11:02 UTC, sergeybv26 commented on drevo/models/questions.py
> +        null=True,
Я ссылку на документацию дал для изучения теории

2023-10-26 11:14 UTC, Allecs43rus commented on drevo/models/questions.py
> +        default=0
Так мы позволяем ввести NULL или нет? Или  я не правильно документацию прочитал. blank проверяет ввод на NULL  значение? По умолчанию blank=false, а значит не пропускает пустое значение?

2023-10-26 14:05 UTC, sergeybv26 reviewed
Нужно миграцию создать

2023-10-26 14:34 UTC, sergeybv26 approved these changes

2023-10-26 14:36 UTC, merged