Создание глоссария версия 2
lvb555/derzn pull request #732
Opened 2023-10-25 13:56 UTC by jksdghfhjkas

Создана модель GlossaryCategories в файле drevo/models/category_glossary.py, модель GlossaryTerms дополнена. Реализована реформа страницы глоссария.

2023-10-25 18:12 UTC, sergeybv26 requested changes

2023-10-25 18:12 UTC, sergeybv26 commented on drevo/models/category_glossary.py
> +        null=True,
Думаю лучше установить значение по умолчанию вместо NULL

2023-10-25 18:12 UTC, sergeybv26 commented on drevo/views/glossary_list_view.py
> +            for value in GlossaryCategories.objects.all() if bool(GlossaryTerm.objects.filter(category=value)) != False
Слишком много запросов в БД. Нужно оптимизировать

2023-10-26 08:26 UTC, jksdghfhjkas commented on drevo/views/glossary_list_view.py
> +            for value in GlossaryCategories.objects.all() if bool(GlossaryTerm.objects.filter(category=value)) != False
Такое решение подойдет?
`       categories = GlossaryCategories.objects.all()
        terms = GlossaryTerm.objects.filter(is_published=True)

        set_categories_terms = [
            {
                'name_category': value.name,
                'set_terms': terms.filter(category=value).order_by(way_of_sorting)
            }
            for value in categories if bool(terms.filter(category=value)) != False
        ]`

2023-10-26 08:27 UTC, jksdghfhjkas commented on drevo/views/glossary_list_view.py
> +            for value in GlossaryCategories.objects.all() if bool(GlossaryTerm.objects.filter(category=value)) != False
Такое решение подойдет?`        categories = GlossaryCategories.objects.all()
        terms = GlossaryTerm.objects.filter(is_published=True)

        set_categories_terms = [
            {
                'name_category': value.name,
                'set_terms': terms.filter(category=value).order_by(way_of_sorting)
            }
            for value in categories if bool(terms.filter(category=value)) != False
        ]`

2023-10-26 10:58 UTC, sergeybv26 requested changes

2023-10-26 10:58 UTC, sergeybv26 commented on drevo/views/glossary_list_view.py
> +        categories = GlossaryCategories.objects.all()
В этом запросе можно сделать фильтрацию

2023-10-26 10:58 UTC, sergeybv26 commented on drevo/views/glossary_list_view.py
> +            for value in categories if bool(terms.filter(category=value)) != False
На каждую итерацию цикла будет отдельный запрос в БД. Такое решение не пойдет

2023-10-26 10:58 UTC, sergeybv26 commented on drevo/views/glossary_list_view.py
> +            for value in GlossaryCategories.objects.all() if bool(GlossaryTerm.objects.filter(category=value)) != False
Не подойдет. На каждую итерацию цикла будет отдельный запрос в БД

2023-10-26 14:52 UTC, jksdghfhjkas commented on drevo/views/glossary_list_view.py
> +            for value in GlossaryCategories.objects.all() if bool(GlossaryTerm.objects.filter(category=value)) != False
я сделал вот такой вывод в get_queryset

return [{
       'name_category': GlossaryCategories.objects.filter(glossaryterm__isnull=False).distinct(),
       'set_terms': GlossaryTerm.objects.filter(is_published=True).order_by(way_of_sorting)
}]

а в шаблоне glossary.html с помощью двух циклов сделал отображение. Мне делать pull request с этими исправлениями?

2023-10-26 14:53 UTC, jksdghfhjkas commented on drevo/models/category_glossary.py
> +        null=True,
я заменил null=True на default=0

2023-10-27 14:32 UTC, closed without merging