Editorial staff
lvb555/derzn pull request #845
Opened 2024-03-22 08:44 UTC by Akilo27

сделал 1 и 2 задачу ТЗ

2024-03-22 08:50 UTC, sergeybv26 requested changes

2024-03-22 08:50 UTC, sergeybv26 commented on drevo/views/editorial_staff.py
> +        experts.append(User.objects.get(id=i))
Совсем не оптимально. Можно сделать одним запросом в БД при получении SpecialPermissions

2024-03-22 09:40 UTC, RomanBorovskiy commented on drevo/templates/admin/drevo/knowledge/editorial_staff_template.html
>      <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
JQuery уже загружен в base.html, правда версии 3.1.1

2024-03-22 09:50 UTC, RomanBorovskiy commented on drevo/views/editorial_staff.py
>  @csrf_exempt
csrf_exempt( просмотр ) [¶](https://djangodoc.ru/3.2/ref/csrf/?ysclid=lu2h5bl8so171829046#django.views.decorators.csrf.csrf_exempt)
    Этот декоратор отмечает, что представление освобождается от защиты, обеспечиваемой промежуточным программным обеспечением

Этот эндпойнт вносит важные изменения в базу. При этом отключена защита CSRF?

2024-03-29 18:34 UTC, sergeybv26 reviewed
Еще немного осталось добить и будет хорошо.

2024-03-29 18:34 UTC, sergeybv26 commented on drevo/templates/admin/drevo/knowledge/editorial_staff_template.html
> +    <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
Роман имел ввиду, что зачем еще раз подключать JQuery, если он подключен в base.html, а базовый шаблон подключается в строке 1

2024-03-29 18:34 UTC, sergeybv26 commented on drevo/views/editorial_staff.py
> +        experts = [sp.expert for sp in special_permissions]
Тоже не оптимально. Разве нельзя сделать выборку в строке 16?

2024-03-29 18:34 UTC, sergeybv26 commented on drevo/views/editorial_staff.py
> +        print(permissions, group)
Нужно очистить от отладочных команд

2024-03-30 11:39 UTC, Akilo27 commented on drevo/views/editorial_staff.py
> +        experts = [sp.expert for sp in special_permissions]
Сергей,  я не совсем понимаю, как можно ещё больше оптимизировать эту часть кода, ведь мне нужно в шаблоне одновременно использовать и "special_permissions", и "experts". 

Я могу поменять "select_related" на "prefetch_related" для скорости кода, и тогда будет 2 запроса к базе данных:

1. Выполняется запрос к базе данных для извлечения всех объектов SpecialPermissions с предварительной загрузкой связанных экспертов.

2. Создается список экспертов из объектов SpecialPermissions.
Это происходит потому, что при использовании prefetch_related('expert') , Django выполняет один запрос для получения всех связанных объектов Expert сразу, что помогает уменьшить общее количество запросов к базе данных.

Вы имеете ввиду, что я могу получить 2 значения за 1 запрос к бд и сделать это быстрее?

2024-03-30 16:08 UTC, RomanBorovskiy commented on drevo/views/editorial_staff.py
>  def update_roles(request):
форму может вызывать только superuser?  Тогда здесь тоже должна быть проверка if request.user.is_superuser: ....., иначе классическая дыра в безопасности - любой `зарегистрированный` пользователь может поднять себе права до superuser

2024-03-31 10:17 UTC, sergeybv26 approved these changes

2024-03-31 14:29 UTC, merged