Созданы страницы interview_table и interviews_all
lvb555/derzn pull request #846
Opened 2024-03-30 10:04 UTC by Suleiman017

Страница interview_table показывает интервью в котором находится таблица с авторами и их ответами на вопросы заданные в этом интервью. Страница interviews_all показывает все категории в которых находятся интервью период которых уже истек

2024-03-30 11:57 UTC, sergeybv26 requested changes

2024-03-30 11:57 UTC, sergeybv26 commented on drevo/views/interview_table_view.py
> +    author_names = {}
authors_dict и author_names можно заменить на defaultdict и исключить 24 строку

2024-03-30 11:57 UTC, sergeybv26 commented on drevo/views/interview_table_view.py
> +                profile = Profile.objects.get(user=author.user_author)
Нельзя ли избавиться от этого запроса? Совсем не оптимально получается

2024-03-30 11:57 UTC, sergeybv26 commented on drevo/views/interview_table_view.py
> +# from django.shortcuts import render, get_object_or_404
Если код закомментирован, то он не нужен

2024-03-30 16:09 UTC, RomanBorovskiy commented on drevo/views/interviews_all_view.py
> +from datetime import timedelta
либо грузи модуль и используй его (datetime.timedelta), либо грузи только те объекты, что нужны. Не ошибка, но выглядит странно

2024-03-30 16:09 UTC, RomanBorovskiy commented on drevo/views/interviews_all_view.py
>                      the_end_of_period = list_period_interview[11:]
Если я правильно понял зачем это - на периоде типа '20.11.20-21.11.20' этот код будет работать плохо.  
Для этого обычно используют str.split('-'), не надо преобразовывать в список, потом обратно

2024-03-30 16:09 UTC, RomanBorovskiy commented on drevo/views/interview_table_view.py
> +    questions_dict = {question.rz.name: question.rz.name for question in questions}
вопросы потом идентифицируешь по name? Можно, конечно, name уникально.  Но по id быстрее получится. Потому что для запроса bz__name=question.rz.name по факту надо две таблицы соединить. А bz__id = question__id по одной таблице пойдет. И зачем вообще словарь нужен? Используй список, если нужны только названия, либо заполняй rz.id: rz.name, если действительно нужен функционал словаря

2024-03-30 16:29 UTC, RomanBorovskiy commented on drevo/views/interview_table_view.py
> +                profile = Profile.objects.get(user=author.user_author)
Согласен,  бегать по всем авторам - это перебор. А если их миллионы? Тебе же нужен конкретный автор - автор ответа на вопрос

2024-03-31 07:01 UTC, Suleiman017 commented on drevo/views/interview_table_view.py
> +    questions_dict = {question.rz.name: question.rz.name for question in questions}
Здравствуйте, я использую  bz__name=question.rz.name т.к. мне же нужно чтобы были одинаковы названия вопроса, а то что вы сказали bz__id = question__id не совсем неверно потому что questions это связи с типом связи состав а asnwers - Ответ и когда я пишу question__id то выходит что я хочу чтобы выводились все связи с одинаковыми id, но если вы имели в виду bz__id=question.rz.id, то тогда спасибо за замечание.

2024-03-31 08:40 UTC, Suleiman017 commented on drevo/views/interview_table_view.py
> +    questions_dict = {question.rz.name: question.rz.name for question in questions}
Здравствуйте, я использую bz__name=question.rz.name т.к. мне же нужно чтобы были одинаковы названия вопроса, а то что вы сказали bz__id = question__id не совсем неверно потому что questions это связи с типом связи состав а asnwers - Ответ и когда я пишу question__id то выходит что я хочу чтобы выводились все связи с одинаковыми id, но если вы имели в виду bz__id=question.rz.id, то тогда спасибо за замечание.

2024-03-31 10:32 UTC, sergeybv26 commented on drevo/views/interview_table_view.py
> +            profile = Profile.objects.get(user=author.user_author)
Лучше сделать получение профиля не в цикле, а вместе с answers. Кроме того получение автора сделано не самым оптимальным способом. Запросов к БД в цикле не должно быть

2024-04-02 16:06 UTC, RomanBorovskiy requested changes

2024-04-02 16:06 UTC, RomanBorovskiy commented on drevo/views/interview_table_view.py
> +            for profile in profiles:
1. Профиль больше не нужен, чтобы получить отчество, все в модели User
2. Если бы был нужен, реализация так себе - перебирать все профили в надежде что один из них будет профилем пользователя не оптимально

2024-04-02 16:06 UTC, RomanBorovskiy commented on drevo/views/interviews_all_view.py
> +                        print(the_end_of_period)
отладочный вывод

2024-04-02 16:06 UTC, RomanBorovskiy commented on drevo/views/interviews_all_view.py
> +                        print(the_end_of_period)
отладочный вывод

2024-04-02 16:06 UTC, RomanBorovskiy commented on drevo/views/interviews_all_view.py
> +                    except(ValueError):
Судя по коду дальше - отлавливаешь лишние пробелы. Так удали их

2024-04-02 16:06 UTC, RomanBorovskiy commented on drevo/views/interviews_all_view.py
>      interviews = Znanie.objects.filter(tz_id=tz_id, is_published=True)
Постарайся одним запросом выбрать записи с полями: Категория, Интервью, Период

2024-04-22 09:03 UTC, closed without merging