Document template
lvb555/derzn pull request #850
Opened 2024-04-02 07:21 UTC by Dinarchak

Pull request к задаче https://github.com/lvb555/derzn/issues/799

2024-04-02 08:19 UTC, RomanBorovskiy commented on drevo/forms/variable_form.py
> +        if connected_to is not None and connected_to.availability < availability:
`if connected_to` можно написать наверное

2024-04-02 08:28 UTC, RomanBorovskiy commented on drevo/forms/variable_form.py
> +            raise f'Родителем {l[availability]} объекта не может быть {l[connected_to.availability]} объект'
raise <Exception> должно быть

2024-04-02 08:48 UTC, RomanBorovskiy commented on drevo/templates/drevo/document_text_template/objects_tree.html
>  	<script type="application/javascript" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
JQuery уже загружается в base.html

2024-04-02 09:00 UTC, RomanBorovskiy commented on drevo/views/document_text_template/save_text_template.py
> +    if objects is not None:
Можно просто - if objects:

2024-04-02 09:25 UTC, RomanBorovskiy commented on drevo/views/document_text_template/save_text_template.py
> +        for i in objects:
Поясни что здесь происходит.  Удаляются все имеющиеся связи а потом в цикле создаешь новые? А может быть ситуация, что создаются такие же связи их не надо было удалять?

2024-04-02 10:17 UTC, RomanBorovskiy requested changes

2024-04-02 10:17 UTC, RomanBorovskiy commented on drevo/forms/variable_form.py
> +        print(self.fields)
вывод для дебага?

2024-04-02 10:17 UTC, RomanBorovskiy commented on drevo/forms/variable_form.py
> +            raise f'Родителем {l[availability]} объекта не может быть {l[connected_to.availability]} объект'
raise Exception должно быть

2024-04-02 10:17 UTC, RomanBorovskiy commented on drevo/views/document_text_template/save_text_template.py
> +        for i in objects:
Поясни что здесь происходит. Удаляются все имеющиеся связи а потом в цикле создаешь новые? А может быть ситуация, что создаются такие же связи их не надо было удалять?

2024-04-03 10:08 UTC, Dinarchak commented on drevo/views/document_text_template/save_text_template.py
> +        for i in objects:
В шаблона текста(на странице edit_text_template) пользователь может вставлять объекты(переменные), в шаблон своего текста. Если в какой-то момент пользователь хочет удалить объект, то я должен знать, что он нигде не используется. Поэтому  при сохранении шаблона(и перед удалением объекта) я фиксирую, какие объекты входят в шаблона и перезаписываю их. Делаю так, потому что нет четкого момента, когда пользователь стирает объект из шаблона. Это можно отслеживать по нажатию клавиш, но то как есть сейчас проще

2024-04-03 10:33 UTC, RomanBorovskiy commented on drevo/views/document_text_template/save_text_template.py
> +        for i in objects:
Сколько может быть переменных? Они же не все каждый раз все удаляются пользователем? Получается, что: 1) zn.template_objects_set.clear() - одним запросом ты все удаляешь из базы.  2) zn.template_objects_set.add(TemplateObject.objects.get(id=int(i))) - двумя запросами получаешь TemplateObject по id и вторым записываешь его в базу.  Для N объектов будет 2*N +1 запросов в базу.  Причем возможно переменные даже не менялись.

2024-04-03 16:16 UTC, RomanBorovskiy approved these changes

2024-04-05 20:56 UTC, merged