Поправки interviews_all, interview_table и их css
lvb555/derzn pull request #861
Opened 2024-04-07 10:29 UTC by Suleiman017

2024-04-07 13:52 UTC, RomanBorovskiy requested changes

2024-04-07 13:52 UTC, RomanBorovskiy commented on drevo/views/interview_table_view.py
> +            authors_dict[author.name][question.rz.name].append(answer.rz.name)
Что будет, если у авторы - полные тезки?

2024-04-07 13:52 UTC, RomanBorovskiy commented on drevo/views/interview_table_view.py
> +        answers = Relation.objects.filter(tr__name="Ответ", bz__id=question.rz.id).select_related('rz__author').all()
Уже лучше, но посмотри вариант сделать через bz__in = [список вопросов]. За один запрос работает

2024-04-07 13:52 UTC, RomanBorovskiy commented on drevo/views/interview_table_view.py
> +            author = answer.rz.author
У знания есть поле user. Нельзя ли его использовать сразу, вместо того чтобы по author получать user?

2024-04-07 13:52 UTC, RomanBorovskiy commented on drevo/views/interviews_all_view.py
> +    interviews_prefetch = Prefetch(
Не проще ли выбрать связи "Период интервью" и взять у базового знания категорию?

2024-04-12 10:01 UTC, Suleiman017 commented on drevo/views/interview_table_view.py
> +            author = answer.rz.author
Здравствуйте поле user не заполняется. поэтому я беру все из author, иначе если я это сделаю будет выводиться первый попавшийся пользователь

2024-04-12 10:50 UTC, RomanBorovskiy commented on drevo/views/interview_table_view.py
> +            author = answer.rz.author
Как минимум в тестовой базе все знания с заполненым полем user, думаю так по умолчанию везде сделано при создании знания, тем более user пустым быть не может в модели Znanie

2024-04-13 10:14 UTC, Suleiman017 commented on drevo/views/interview_table_view.py
> +            author = answer.rz.author
Спасибо за замечание я понял в чем проблема, оказалось что user этот тот который создал знание, а я делал все ответы на одном и том же аккаунте из-за этого выводился не тот пользователь. Сейчас я снова переделал оба файла и можете посмотреть на изменения

2024-04-16 09:40 UTC, RomanBorovskiy requested changes

2024-04-16 09:40 UTC, RomanBorovskiy commented on drevo/views/interview_table_view.py
> +        answers = Relation.objects.filter(tr__name="Ответ", bz__in=question_list).select_related('rz__author').all()
зачем в цикле каждый раз делать один и тот же запрос?

2024-04-16 09:40 UTC, RomanBorovskiy commented on drevo/views/interviews_all_view.py
> +        period = Relation.objects.filter(bz=interview, bz__category=interview.category, tr__name="Период интервью", ).first()
На каждое интервью ты делаешь отдельный запрос и получаешь период интервью. Исходи из того, что запрос к БД - это дорого. Предлагаю выбрать ВСЕ связи "Период интервью" с необходимыми полями одним запросом, а потом обрабатывать полученный dataset - миллионов записей здесь пока не планируется. Здесь не настолько сложная логика, можно же за один раз все получить

2024-04-16 09:40 UTC, RomanBorovskiy commented on drevo/views/interview_table_view.py
> +                author = answer.rz.author
Нужен ли теперь author? Имя берешь от user,  можешь же user.id использовать, а не author.id

2024-04-17 11:22 UTC, Suleiman017 commented on drevo/views/interview_table_view.py
> +                author = answer.rz.author
Уже изменено

2024-04-22 09:02 UTC, closed without merging