Еще поправки view
lvb555/derzn pull request #870
Opened 2024-04-21 13:19 UTC by Suleiman017

2024-04-22 09:01 UTC, RomanBorovskiy requested changes

2024-04-22 09:01 UTC, RomanBorovskiy commented on drevo/views/interviews_all_view.py
> +                for category_interview in category_interviews:
Это плохо, итерирование по списку медленно работает. Перебираешь все категории в надежде найти нужную? Если на то пошло, ищи в списке встроенными функциями типа index либо сделай словарь my_dict = {category: [knowledge,]} и проверяй на вхождение в словарь: category in my_dict. Или даже так: my_dict.setdefault(category, []).append(knowledge)

2024-04-22 09:01 UTC, RomanBorovskiy commented on drevo/views/interviews_all_view.py
> +    periods = Relation.objects.filter(tr__name="Период интервью")
Можно сразу подгрузить необходимы модели (bz, rz__name, bz__category)

2024-04-22 09:01 UTC, RomanBorovskiy commented on drevo/views/interview_table_view.py
> +        for answer in answers:
При таком подходе ты пройдешь список ответов несколько раз (по количеству вопросов). Зачем цикл по questions? question.rz == answer.bz. Можно сделать все одним циклом.
У ответов могут повторяться авторы. Надо ли каждый раз генерировать имя?

2024-04-25 03:02 UTC, Suleiman017 commented on drevo/views/interview_table_view.py
> +        for answer in answers:
Здравствуйте, @RomanBorovskiy я понял что вы имеете в виду, и уже переписал свой код

2024-04-25 07:46 UTC, RomanBorovskiy requested changes

2024-04-25 07:46 UTC, RomanBorovskiy commented on drevo/views/interview_table_view.py
>      answers = Relation.objects.filter(tr__name="Ответ", bz__in=question_list).select_related('rz__author').all()
rz__author уже не нужен. Но нужны rz__user, rz__name.....

2024-04-25 07:46 UTC, RomanBorovskiy commented on drevo/views/interview_table_view.py
>      questions = Relation.objects.filter(tr__name="Состав", bz__id=interview.id)
Здесь неплохо бы сразу rz подтянуть....

2024-04-25 13:27 UTC, Suleiman017 commented on drevo/views/interview_table_view.py
>      questions = Relation.objects.filter(tr__name="Состав", bz__id=interview.id)
@RomanBorovskiy, уже изменено

2024-04-25 16:35 UTC, Suleiman017 commented on drevo/views/interview_table_view.py
>      answers = Relation.objects.filter(tr__name="Ответ", bz__in=question_list).select_related('rz__author').all()
@RomanBorovskiy я уже сделал select_related('rz__user') но когда попытался сделать тоже самое с rz__name вышла ошибка, поэтому  я сделал не rz__name а просто rz

2024-04-26 07:57 UTC, RomanBorovskiy commented on drevo/views/interview_table_view.py
>      answers = Relation.objects.filter(tr__name="Ответ", bz__in=question_list).select_related('rz__author').all()
Так правильно, rz__name  же не модель отдельная связанная, а поле... Я имел в виду что в запросе подгружаешь не то, что тебе требуется, зато потом отдельными запросами загружаешь данные. 
name_of_rz  = answers.rz.name по факту сделает отдельный запрос к базе

2024-04-26 08:42 UTC, RomanBorovskiy requested changes

2024-04-26 08:42 UTC, RomanBorovskiy commented on drevo/views/interview_table_view.py
> +        question = answer.bz
Либо модель подгружай, либо bz_id используй

2024-04-26 08:42 UTC, RomanBorovskiy commented on drevo/views/interviews_all_view.py
>  #     now = datetime.datetime.now()
Закомментированный код, особенно в таком объеме - не хорошо. Для истории изменений есть git

2024-04-27 16:47 UTC, Suleiman017 commented on drevo/views/interview_table_view.py
> +        question = answer.bz
@RomanBorovskiy Обновлено

2024-05-02 05:33 UTC, closed without merging