Создание страницы "Дерево необработанных предложений пользователей
lvb555/derzn pull request #901
Opened 2024-06-14 20:42 UTC by Akilo27

Структура страницы

1) Заголовок и "хлебные крошки"

2) Дерево знаний с НЕОБРАБОТАННЫМИ предложениями в пределах компетенции пользователя - руководителя.

На вершине знания, имеющего еще необработанные предложения появляется пиктограмма "Предложения", при нажатии на которую возникает страница "Обработка предложений по знанию".

Логика построения дерева необработанных предложений

Для построения дерева используется таблица "Предложения пользователей" (Suggestion from admin).

1) Нужно получить список знаний, содержащих хотя бы одну необработанную запись-предложение. Реквизит "Результат проверки" = "Неизвестно"

2) На основе этого этого списка знаний построить 2-й список знаний, лежащих в рамках компетенций руководителя, т.е. в рамках категорий, доступных ему для работы.

3) На основе 2-го списка знаний построить дерево знаний, используя модуль построения дерева. 4) На вершинах знаний из 2-го списка расположить пиктограммы "Предложения" для перехода на страницу "Обработка предложений пользователя".

вся задача - https://github.com/lvb555/derzn/issues/770

2024-06-15 11:23 UTC, RomanBorovskiy requested changes

2024-06-15 11:23 UTC, RomanBorovskiy commented on drevo/views/zn_constructors/general_views.py
> +        is_constructor_type = 'suggestion'
эти 2 переменные больше нигде не используются? В контекст они не идут

2024-06-15 11:23 UTC, RomanBorovskiy commented on drevo/templates/drevo/tags/knowledge_nodes.html
> +        {% if is_constructor_type != 'suggestion' %}
Для чего это условие? Выглядит лишним

2024-06-15 12:10 UTC, Akilo27 commented on drevo/templates/drevo/tags/knowledge_nodes.html
> +        {% if is_constructor_type != 'suggestion' %}
без этого условия, показывается лишняя иконка, которой быть не должно. Попытался без него, всё равно показывается.

2024-06-15 14:07 UTC, RomanBorovskiy commented on drevo/templates/drevo/tags/knowledge_nodes.html
> +        {% if is_constructor_type != 'suggestion' %}
Точно, не заметил где условие закончилось

2024-06-15 14:11 UTC, RomanBorovskiy requested changes

2024-06-15 14:11 UTC, RomanBorovskiy commented on drevo/templates/drevo/tags/knowledge_nodes.html
> +        <a href="/drevo/znanie/{{ base_knowledge.id }}/suggestions"><i class="fa fa-info-circle">предложения</i></a>
здесь желательно использовать {% url 'create-suggestion'  base_knowledge.id %}, а не указывать hard link

2024-06-16 13:09 UTC, sergeybv26 approved these changes

2024-06-17 11:15 UTC, RomanBorovskiy approved these changes

2024-06-17 20:07 UTC, merged