Две таблицы в одном view
lvb555/derzn pull request #903
Opened 2024-06-18 08:27 UTC by Suleiman017

2024-06-19 10:58 UTC, RomanBorovskiy requested changes

2024-06-19 10:58 UTC, RomanBorovskiy commented on drevo/templates/drevo/dimensional_distributions_1.html
> +<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
jquery не нужен, уже есть в base.html

2024-06-19 10:58 UTC, RomanBorovskiy commented on drevo/templates/drevo/dimensional_distributions_1.html
> +<head>{% block title %}Одномерные распределениия{% endblock %}</head>
head не нужен. Опечатка - распределен_и_я

2024-06-19 10:58 UTC, RomanBorovskiy commented on drevo/templates/drevo/dimensional_distributions_2.html
> +<head>{% block title %}Двумерные распределения{% endblock %}</head>
head не нужен

2024-06-19 10:58 UTC, RomanBorovskiy commented on drevo/templates/drevo/interview_table.html
>  <head><title>{% block title %}Авторы Интервью{% endblock %}</title></head>
head title не нужны

2024-06-19 10:58 UTC, RomanBorovskiy commented on drevo/templates/drevo/interviews_all.html
> +<head>{% block title %}Все интервью{% endblock %}</head>
head не нужен

2024-06-19 10:58 UTC, RomanBorovskiy commented on drevo/urls.py
> +    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
что здесь меняется? если ничего существенного  - не надо такие изменения в коммиты добавлять

2024-06-19 10:58 UTC, RomanBorovskiy commented on drevo/views/interviews_statistics_view.py
> +    questions = list(set(InterviewAnswerExpertProposal.objects.filter(
Здесь и ниже - зачем нужна конструкция list(set())?  Удалить повторы? distinct это сделает

2024-06-19 10:58 UTC, RomanBorovskiy commented on drevo/views/interviews_statistics_view.py
> +    answers = InterviewAnswerExpertProposal.objects.filter(
Здесь не требуется использовать фильтр еще и по интервью? Вопросы же могут в разных интервью повторяться?

2024-06-19 10:58 UTC, RomanBorovskiy commented on drevo/views/interviews_statistics_view.py
> +    selected_question = request.GET.get('selected_question')
Рекомендую в качестве идентификаторов использовать id (pk), а не строковое имя объекта

2024-06-19 10:58 UTC, RomanBorovskiy commented on drevo/views/interviews_statistics_view.py
> +    total_voters = answers.values('expert').distinct().count()
Если вопрос используется в нескольких интервью - это число экспертов согласных со всеми ответами на этот вопрос во всех интервью?
Если вопрос используется точно в одном интервью - то это число экспертов согласных с ответами на вопросы интервью. Чем отличается от значения ниже?

2024-06-19 10:58 UTC, RomanBorovskiy commented on drevo/views/interviews_statistics_view.py
> +            table = [{'answer_name': answer_id,
Список table точно должен создаваться в цикле каждый раз?

2024-06-19 10:58 UTC, RomanBorovskiy commented on drevo/views/interviews_statistics_view.py
> +                common_experts[answer_1][answer_2]['percentage'] = (common_experts[answer_1][answer_2]['count'] / total_counts[answer2]) * 100 if total_counts[answer2] > 0 else 0
Поясни алгоритм расчета.  Считаешь total, percentage,  потом пересчитываешь?
И что значат эти цифры на странице

![изображение](https://github.com/lvb555/derzn/assets/59736627/72ee708d-8ce5-4914-b301-6622d1ab2283)

2024-06-21 07:42 UTC, Suleiman017 commented on drevo/views/interviews_statistics_view.py
> +            table = [{'answer_name': answer_id,
@RomanBorovskiy Уже обновлено

2024-06-26 10:45 UTC, RomanBorovskiy requested changes

2024-06-26 10:45 UTC, RomanBorovskiy commented on drevo/templates/drevo/dimensional_distributions_2.html
> +            {% if selected_question_1 and not selected_question_2 %}
как это условие сочетается с условием выше?

2024-06-26 10:45 UTC, RomanBorovskiy commented on drevo/templates/drevo/dimensional_distributions_2.html
> +    {% endif %}
Очень сложная простыня из условий. И при этом не работает как надо - списки все равно скидываются на Вопрос-1 и Вопрос-2. Попробуй логику сделать на JS - может проще будет
![изображение](https://github.com/lvb555/derzn/assets/59736627/4308458c-0940-4619-b941-e454616fd2cc)

2024-06-26 10:45 UTC, RomanBorovskiy commented on drevo/views/interviews_statistics_view.py
> +    table = []
получается это лишнее, таблица потом создается

2024-06-26 10:45 UTC, RomanBorovskiy commented on drevo/views/interviews_statistics_view.py
> +            all_answers[answer_id] += agreed_count
Зачем вся эта конструкция? Перекладываешь queryset answers в словарь? Данные такие же будут

2024-06-26 10:45 UTC, RomanBorovskiy commented on drevo/views/interviews_statistics_view.py
> +        total_counts[answer2] = InterviewAnswerExpertProposal.objects.filter(
вызывать запрос в цикле - это не хорошо, попробуй одним запросом

2024-06-26 10:45 UTC, RomanBorovskiy commented on drevo/views/interviews_statistics_view.py
> +            cell['percentage'] = (cell['count'] / row['totals'][i]) * 100 if row['totals'][i] > 0 else 0
Распиши алгоритм в комментариях. Непонятно что делаешь и зачем. answers_1, answers_2 - все ответы на вопрос во всех интервью, даже если он None или эксперт с ним не согласен? Не проще ли статистику по таблице считать, когда она заполнена, а не отдельными запросами?
И как получается, что проголосовало 0 человек, а всего 2?
![изображение](https://github.com/lvb555/derzn/assets/59736627/c25b00bb-506d-41e9-8f72-8538c3e0f05b)

2024-07-01 13:08 UTC, Suleiman017 commented on drevo/views/interviews_statistics_view.py
> +            cell['percentage'] = (cell['count'] / row['totals'][i]) * 100 if row['totals'][i] > 0 else 0
@RomanBorovskiy Уже обновлено и исправлено

2024-07-02 09:25 UTC, RomanBorovskiy requested changes

2024-07-02 09:25 UTC, RomanBorovskiy commented on drevo/views/interviews_statistics_view.py
> +        all_answers[answer_id] = agreed_count
Зачем заполнять словарь, если сразу можно table по answers заполнить?

2024-07-02 09:25 UTC, RomanBorovskiy commented on drevo/views/interviews_statistics_view.py
> +                common_experts[answer_1][answer_2]['total'] = total_common_experts
total_common_experts - у тебя это одно значение для всех вариантов = количество экспертов, давших ответ "согласен" на вопрос 1 и 2 в интервью. Смысл его отдельно сохранять в поле таблицы?

2024-07-02 09:25 UTC, RomanBorovskiy commented on drevo/views/interviews_statistics_view.py
> +            total_count_for_answer2 = common_experts[answer1][answer2]['total']
Здесь будет 0, если common_experts[answer_1][answer_2]['count']==0, total_common_experts в остальных случаях. То есть константа с условием. Зачем в списке хранить?
![изображение](https://github.com/lvb555/derzn/assets/59736627/b238f8db-3e31-4140-98ba-22d2d483a93e)
Всего проголосовавших - что предполагается? Если это число экспертов, проголосовавших по вопросу 1 и 2 - почему оно разное? Если это число проголосовавших по вопросу 2 - почему арифметика не бьется?

2024-07-02 09:25 UTC, RomanBorovskiy commented on drevo/views/interviews_statistics_view.py
> +        if question.question not in question_list:
question.question вызовет многократные запросы. Надо выбрать все в одном запросе. И не проще ли весь список получить запросом, если надо - в list преобразовать?

2024-07-04 04:38 UTC, Suleiman017 commented on drevo/views/interviews_statistics_view.py
> +            total_count_for_answer2 = common_experts[answer1][answer2]['total']
g

2024-07-05 16:18 UTC, Suleiman017 commented on drevo/views/interviews_statistics_view.py
> +        if question.question not in question_list:
@RomanBorovskiy Прошу проверить изменения

2024-07-08 18:54 UTC, RomanBorovskiy commented on drevo/views/interviews_statistics_view.py
> +        if question.question not in question_list:
Так должно быть?
![изображение](https://github.com/lvb555/derzn/assets/59736627/67b67db0-dd60-4d01-9ae0-628502557996)

2024-07-09 17:10 UTC, RomanBorovskiy approved these changes

2024-07-09 17:10 UTC, RomanBorovskiy commented on drevo/views/interviews_statistics_view.py
> +    return render(request, 'drevo/dimensional_distributions_2.html', context)
Так должно быть?
![изображение](https://github.com/lvb555/derzn/assets/59736627/ee389bf9-e75b-4b5a-9034-67dcb05d5e2e)

2024-07-10 11:51 UTC, merged