Document template 3
lvb555/derzn pull request #946
Opened 2024-08-12 17:20 UTC by Dinarchak

Изменения к комментарию https://github.com/lvb555/derzn/issues/799

1. Дерево объектов шаблона документа сортируется по весу объекта
2. Изменения в админ панели
3. Добавлена функция проверки корректности дерева: предупреждать пользователя о группах без наследников.

2024-08-14 13:23 UTC, RomanBorovskiy commented on drevo/views/document_text_template/object_deletion.py
> +            error_text += f'{template.name}, '
Предлагаю здесь использовать error_text += ', '.join([template.name for template in templates_that_use]). Тогда можно будет просто error_text передавать, без обрезания двух последних символов.

2024-08-14 14:06 UTC, RomanBorovskiy commented on drevo/static/drevo/js/template_objects/response_handlers/objects_tree.js
>  export function CreateNewObjec(ans) {
Придирка конечно, но может все же лучше CreateNewObjec**t** назвать функцию? Или так и задумано?

2024-08-14 14:34 UTC, RomanBorovskiy commented on drevo/static/drevo/js/template_objects/response_handlers/requirements.js
> +			r = w - 1
Опасно. Если w подходит под условие, не факт, что w-1 подойдет.  Надо r=w.  В массиве [10, 20, 30] поищи 15 - найдет 10

2024-08-14 15:46 UTC, RomanBorovskiy commented on drevo/views/document_text_template/object_processing.py
>                  obj_to_return = TemplateObject.objects.create(
Названия параметров совпадают? Можно сделать красиво TemplateObject.objects.create(**form.cleaned_data, user = request.user). Хотя здесь напрашивается ModelForm. Заодно там и входные значения проверять можно

2024-08-14 15:51 UTC, RomanBorovskiy requested changes
Небольшие замечания

2024-08-15 08:03 UTC, RomanBorovskiy commented on drevo/views/document_text_template/object_processing.py
>              form.cleaned_data['fill_title'] = form.cleaned_data['fill_title'] if form.cleaned_data['fill_title'] is not None else ''
Можно короче:  form.cleaned_data['fill_title'] or ''

2024-08-15 16:47 UTC, Dinarchak commented on drevo/static/drevo/js/template_objects/response_handlers/objects_tree.js
>  export function CreateNewObjec(ans) {
Нет, это опечаточка:)

2024-08-15 16:54 UTC, Dinarchak commented on drevo/views/document_text_template/object_processing.py
>                  obj_to_return = TemplateObject.objects.create(
Честно, когда писал этот код думал о ModelForm, но что-то меня оттолкнуло от него и я решил реализовать через обычный Form. Не помню что именно.

2024-08-15 20:05 UTC, RomanBorovskiy approved these changes

2024-08-16 18:17 UTC, merged