suggestion
lvb555/derzn pull request #955
Opened 2024-08-14 17:13 UTC by Akilo27

2024-08-15 10:47 UTC, RomanBorovskiy requested changes

2024-08-15 10:47 UTC, RomanBorovskiy commented on drevo/views/site_pages.py
> +                    query.add(Q(**{key: True}), Q.AND)
здесь и дальше словарь же сам создаешьиз одного значения, а потом раскрываешь. Можно просто Q(key=True). Можно вообще просто словарь с условиями подать в SitePage.objects.filter(**conditions), не используя Q(). У тебя все равно все по AND объединяется. Лишнее усложнение кода

2024-08-15 10:47 UTC, RomanBorovskiy commented on drevo/views/site_pages.py
> +        try:
Можно использовать из drevo.utils.common  функцию validate_parameter_int
Для таких случаев ее и писал) В любом случае нехорошо, что у тебя переменная то числовая, то пустая строковая. Лучше тогда присвоить -1 или None если это не число.

2024-08-19 05:10 UTC, sergeybv26 approved these changes

2024-08-19 05:11 UTC, sergeybv26 commented
После устранения замечаний Романа можно мерджить.

2024-08-19 19:51 UTC, RomanBorovskiy approved these changes

2024-08-22 14:24 UTC, merged