Дискуссии
lvb555/derzn pull request #956
Opened 2024-08-15 07:17 UTC by AlexanderZaramenskikh

Добавлены новые знания дискуссии и соответствующие страницы с правами

2024-08-15 08:24 UTC, RomanBorovskiy requested changes
Не надо в одном pr отправлять коммиты из других pr. Тем более тех, что сейчас на ревью висят и никак логически не связаны с текущей задачей.

2024-08-15 08:24 UTC, RomanBorovskiy commented on drevo/templates/drevo/constructors/tree_constructor.html
> +    {% if type_of_zn == 'algorithm' %}
Условие правильное? Не на дискуссию проверка?

2024-08-15 15:43 UTC, AlexanderZaramenskikh commented on drevo/templates/drevo/constructors/tree_constructor.html
> +    {% if type_of_zn == 'algorithm' %}
Да , правильное , что у документа , что у алгоритма и дискуссии одна логика

2024-08-15 19:09 UTC, RomanBorovskiy commented on drevo/templates/drevo/constructors/tree_constructor.html
> +    {% if type_of_zn == 'algorithm' %}
Так условие получается в блоке else. Оно же не выполнится никогда

2024-08-15 20:23 UTC, AlexanderZaramenskikh commented on drevo/templates/drevo/constructors/tree_constructor.html
> +    {% if type_of_zn == 'algorithm' %}
Вот https://github.com/lvb555/derzn/pull/956/commits/61fdd09307106be007d56d6dc0825769fa378139 поменял , так имели ввиду?

2024-08-16 07:35 UTC, AlexanderZaramenskikh commented on drevo/templates/drevo/constructors/tree_constructor.html
> +    {% if type_of_zn == 'algorithm' %}
https://github.com/lvb555/derzn/pull/956/commits/4b896bfefea063619a3d4d4b31ebe17be6f592c9 исправил

2024-08-17 11:07 UTC, RomanBorovskiy commented on drevo/templates/drevo/constructors/tree_constructor.html
> +    {% elif type_of_zn == 'document' %}
На входе точно будет только три значения из ветки условий? В коде до этого обрабатывались любые значения

2024-08-17 15:41 UTC, AlexanderZaramenskikh commented on drevo/templates/drevo/constructors/tree_constructor.html
> +    {% elif type_of_zn == 'document' %}
Да только три , для других уже другие условия

2024-08-17 19:41 UTC, closed without merging