Like dislike comments
lvb555/derzn pull request #961
Opened 2024-08-17 20:00 UTC by AlexanderZaramenskikh

Like dislike в комментариях

2024-08-19 20:03 UTC, RomanBorovskiy requested changes

2024-08-19 20:03 UTC, RomanBorovskiy commented on custom_admin/urls.py
> +]
Ничего не изменилось?

2024-08-19 20:03 UTC, RomanBorovskiy commented on drevo/views/comment_send_view.py
> +        return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))
redirect_if_referer_not_found - нет такого пути

2024-08-19 20:03 UTC, RomanBorovskiy commented on drevo/views/comment_send_view.py
> +import json
Если не используются импорты - не надо их оставлять

2024-08-19 21:05 UTC, AlexanderZaramenskikh commented on custom_admin/urls.py
> +]
ничего , не меняется случайно добавлено в pr

2024-08-19 21:05 UTC, AlexanderZaramenskikh commented on drevo/views/comment_send_view.py
> +        return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))
https://github.com/lvb555/derzn/pull/961/commits/338fc123e35aa34b4068326786328832bab6a694 исправил

2024-08-19 21:05 UTC, AlexanderZaramenskikh commented on drevo/views/comment_send_view.py
> +import json
https://github.com/lvb555/derzn/pull/961/commits/338fc123e35aa34b4068326786328832bab6a694 исправил

2024-09-10 03:57 UTC, sergeybv26 reviewed
Есть конфликты слияния

2024-10-15 16:10 UTC, closed without merging