add discussion
lvb555/derzn pull request #962
Opened 2024-08-18 18:34 UTC by AlexanderZaramenskikh

добавлены дискусии для экспертов в профиле

2024-08-19 19:57 UTC, RomanBorovskiy requested changes

2024-08-19 19:57 UTC, RomanBorovskiy commented on drevo/views/zn_constructors/general_views.py
> +            if self.type_of_zn == 'algorithm' or self.type_of_zn == 'document' or self.type_of_zn == 'discussion':
Для таких больших условий c or лучше использовать проверку на вхождение:
if self.type_of_zn in ('algorithm', 'document', 'discussion'):

2024-08-19 19:57 UTC, RomanBorovskiy commented on drevo/views/zn_constructors/tree_constructor_view.py
> +            context['title'] = 'Конструктор документа' or "Дискуссии для экспертов"
Опечатка? Всегда будет Конструктор документа

2024-08-19 19:57 UTC, RomanBorovskiy commented on drevo/views/zn_constructors/tree_constructor_view.py
> +            context['relative_znaniya'] = get_descendants_for_knowledge(selected_zn)
Сортировка не нужна больше? Или случайное изменение?

2024-08-19 19:57 UTC, RomanBorovskiy commented on dz/settings.py
> -PYTHONPATH = BASE_DIR.parent / env.str("RELATIVE_PYTHONPATH")
Как это изменение попало в pr? Никак не относится к твоей задаче, да и код старый

2024-08-19 21:00 UTC, AlexanderZaramenskikh commented on drevo/views/zn_constructors/general_views.py
> +            if self.type_of_zn == 'algorithm' or self.type_of_zn == 'document' or self.type_of_zn == 'discussion':
исправил https://github.com/lvb555/derzn/pull/962/commits/701e1b2b77122ecd6ddd57682010bc1dfae21dc8

2024-08-19 21:00 UTC, AlexanderZaramenskikh commented on drevo/views/zn_constructors/tree_constructor_view.py
> +            context['title'] = 'Конструктор документа' or "Дискуссии для экспертов"
https://github.com/lvb555/derzn/pull/962/commits/701e1b2b77122ecd6ddd57682010bc1dfae21dc8 была опечатка

2024-08-19 21:00 UTC, AlexanderZaramenskikh commented on drevo/views/zn_constructors/tree_constructor_view.py
> +            context['relative_znaniya'] = get_descendants_for_knowledge(selected_zn)
https://github.com/lvb555/derzn/pull/962/commits/701e1b2b77122ecd6ddd57682010bc1dfae21dc8 была опечатка

2024-08-19 21:01 UTC, AlexanderZaramenskikh commented on dz/settings.py
> -PYTHONPATH = BASE_DIR.parent / env.str("RELATIVE_PYTHONPATH")
не знаю , когда репозиторий мы тогда обновили это появилось , с этой строчкой не запускалось ничего , вот я и убрал

2024-08-20 09:38 UTC, RomanBorovskiy commented on dz/settings.py
> -PYTHONPATH = BASE_DIR.parent / env.str("RELATIVE_PYTHONPATH")
в develop в репозитории этой строки нет

2024-08-23 15:47 UTC, AlexanderZaramenskikh commented on dz/settings.py
> -PYTHONPATH = BASE_DIR.parent / env.str("RELATIVE_PYTHONPATH")
убрал строку , старая версия была

2024-08-25 17:44 UTC, RomanBorovskiy requested changes

2024-08-25 17:44 UTC, RomanBorovskiy commented on dz/settings.py
> -PYTHONPATH = BASE_DIR.parent / env.str("RELATIVE_PYTHONPATH")
Так убери вообще это изменение из pr

2024-08-26 07:32 UTC, AlexanderZaramenskikh commented on dz/settings.py
> -PYTHONPATH = BASE_DIR.parent / env.str("RELATIVE_PYTHONPATH")
удалил

2024-08-26 07:38 UTC, RomanBorovskiy approved these changes

2024-08-27 13:18 UTC, RomanBorovskiy requested changes
Не надо dz/settings.py удалять вообще

2024-08-28 11:59 UTC, AlexanderZaramenskikh commented
исправил все ошибки , вернул настройки

2024-08-28 12:40 UTC, RomanBorovskiy approved these changes

2024-08-28 13:07 UTC, merged