Issue#949
lvb555/derzn pull request #979
Opened 2024-09-14 19:04 UTC by KudryashovR

#949 

Добавлены:

- Страница "Участие в дискуссии" для экспертов. Позволяет построить дерево связзанных знаний в выбранной дискуссии (url - participation_in_the_discussion/<id_знания_типа_дискуссия>). 
<id_знания_типа_дискуссия> требуется для указания вершины построения дерева.

- Форма новой связи для дискуссии. Сделана по аналогии со страницей "Создание связи".

2024-09-15 15:52 UTC, RomanBorovskiy requested changes
Предлагаю под view создать отдельную папку и хранить там, а не сбрасывать в общую /views - их там стало очень много

2024-09-15 15:52 UTC, RomanBorovskiy commented on drevo/templates/drevo/create_participation.html
> +<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.0/dist/jquery.slim.min.js"></script>
JQuery уже загружен в base.html

2024-09-15 15:52 UTC, RomanBorovskiy commented on drevo/views/participation_in_the_discussion_view.py
> +from pprint import pprint
Для отладки? В коде не используется

2024-09-15 15:52 UTC, RomanBorovskiy commented on drevo/views/create_participation.py
> +from audioop import reverse
Не используется

2024-09-15 15:52 UTC, RomanBorovskiy commented on drevo/templates/drevo/create_participation.html
> +    function fill_tr_field() {
Не проще ли заполнить списки на стороне сервера при рендеринге, чем делать два отдельных запроса из js на сервер?

2024-09-15 16:58 UTC, KudryashovR commented on drevo/templates/drevo/create_participation.html
> +<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.0/dist/jquery.slim.min.js"></script>
Подправлю.

2024-09-15 16:58 UTC, KudryashovR commented on drevo/views/participation_in_the_discussion_view.py
> +from pprint import pprint
Да. Импорт не убрал.

2024-09-15 16:59 UTC, KudryashovR commented on drevo/views/create_participation.py
> +from audioop import reverse
Подправлю

2024-09-15 17:01 UTC, KudryashovR commented on drevo/templates/drevo/create_participation.html
> +    function fill_tr_field() {
Данная логика была взята с аналогичной страницы создания связей. Отдельной страницей делалось только для корректной работы логики возврата на предыдущую страницу по кнопке "Назад".

2024-09-20 08:03 UTC, RomanBorovskiy approved these changes

2024-09-20 20:09 UTC, merged